name: To-do app Integration
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'documentation/**'
    branches:
      - main
      - module_*
      
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'documentation/**'
    branches:
      - main
      - module_*

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: docker build --target test --tag to-do-test-image .

      - name: test
        run: docker run --env-file .env.test to-do-test-image

  build:
    needs: test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/module_8'}}
    name: Create Docker image and push to docker hub
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2

      - run: echo "Publishing"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: philw10/todo-app
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
