name: To-do app Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: docker build --target test --tag to-do-test-image .

      - name: test
        run: docker run --env-file .env.test to-do-test-image