name: To-do app Integration
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'documentation/**'
    branches:
      - main
      - module_*
      
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'documentation/**'
    branches:
      - main
      - module_*


jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: docker build --target test --tag to-do-test-image .

      - name: test
        run: docker run --env-file .env.test to-do-test-image

  build:
    needs: test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/module_8'}}
    name: Create Docker image and push to docker hub
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    
    steps:  
      - uses: actions/checkout@v2        
     
      - run: echo "Publishing"
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: docker build --target production --tag philw10/todo-app:$IMAGE_TAG .

      - name: Push images to Docker hub
        run: docker push philw10/todo-app:$IMAGE_TAG    
          
  deploy:
    needs: build
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "phil-todo-app" 
          heroku_email: "philw10@yahoo.co.uk"  
          usedocker: true
          docker_build_args: |
            NODE_ENV
        env:
          NODE_ENV: production